### ISSUE TITLE
Issue with securing adminer url

### ISSUE THREAD

**Issue by justkidding96** [senaranya/laravel-adminer#5]
Hi,

In your composer.json you autoload the AdminerController. But because of this you can't securing the url.

I've added the following into my web.php:
```php// Adminer
Route::any('adminer', 'SystemController@adminer')->name('adminer')->middleware('auth');
```

But SystemController is never used because of the autoloading.

**Comment by senaranya** [comment]
You need to use AdminerAutologinController to be able to use middleware. See https://github.com/senaranya/laravel-adminer#to-use-adminer-to-laravel-routes-eg-adminer-update-routeswebphp
